-- AlterTable
ALTER TABLE `empresas` MODIFY `status` ENUM('ANALISE', 'APROVADO', 'RECUSADO', 'LIXEIRA') NOT NULL DEFAULT 'ANALISE';

-- AlterTable
ALTER TABLE `usuarios` MODIFY `status` ENUM('APROVADO', 'RECUSADO', 'PENDENTE', 'LIXEIRA') NULL DEFAULT 'PENDENTE';
