-- AlterTable
ALTER TABLE `Leads` ADD COLUMN `annual_investment_next_5_years` DOUBLE NULL,
    ADD COLUMN `arr` DOUBLE NULL,
    ADD COLUMN `breakeven` DOUBLE NULL,
    ADD COLUMN `burnrate` DOUBLE NULL,
    ADD COLUMN `business_model` VARCHAR(191) NULL,
    ADD COLUMN `cash_and_stock_value` DOUBLE NULL,
    ADD COLUMN `current_annual_investment` DOUBLE NULL,
    ADD COLUMN `debt` DOUBLE NULL,
    ADD COLUMN `foundation_date` VARCHAR(191) NULL,
    ADD COLUMN `immobilized` DOUBLE NULL,
    ADD COLUMN `investment_stage` VARCHAR(191) NULL,
    ADD COLUMN `locality` VARCHAR(191) NULL,
    ADD COLUMN `mrr` DOUBLE NULL,
    ADD COLUMN `name_of_person_responsible` VARCHAR(191) NULL,
    ADD COLUMN `ntm` DOUBLE NULL,
    ADD COLUMN `operational_stage` VARCHAR(191) NULL,
    ADD COLUMN `profit_margin` DOUBLE NULL,
    ADD COLUMN `projected_ebitda` DOUBLE NULL,
    ADD COLUMN `projected_revenue_for_the_year` DOUBLE NULL,
    ADD COLUMN `runrate` DOUBLE NULL,
    ADD COLUMN `segmento` VARCHAR(191) NULL,
    ADD COLUMN `site` VARCHAR(191) NULL,
    ADD COLUMN `whatsapp_of_person_responsible` VARCHAR(191) NULL;
